// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtVeUoz7UN6GxMzQuL-jSBFXOODWoA67Q',
    appId: '1:33691177803:web:b3d4cc82bbe538fcbecece',
    messagingSenderId: '33691177803',
    projectId: 'ecommerce-pro-392ca',
    authDomain: 'ecommerce-pro-392ca.firebaseapp.com',
    storageBucket: 'ecommerce-pro-392ca.firebasestorage.app',
    measurementId: 'G-64FGSH2T46',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHgwlQ4PeYqHzQ9WKM77YS2LIjRWnJFII',
    appId: '1:33691177803:android:a391dba7eb87c3dfbecece',
    messagingSenderId: '33691177803',
    projectId: 'ecommerce-pro-392ca',
    storageBucket: 'ecommerce-pro-392ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHQyaR4pCbx94SHTj0kIZY5jyFbNBMqhY',
    appId: '1:33691177803:ios:2b82d2f5a39ce463becece',
    messagingSenderId: '33691177803',
    projectId: 'ecommerce-pro-392ca',
    storageBucket: 'ecommerce-pro-392ca.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHQyaR4pCbx94SHTj0kIZY5jyFbNBMqhY',
    appId: '1:33691177803:ios:2b82d2f5a39ce463becece',
    messagingSenderId: '33691177803',
    projectId: 'ecommerce-pro-392ca',
    storageBucket: 'ecommerce-pro-392ca.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtVeUoz7UN6GxMzQuL-jSBFXOODWoA67Q',
    appId: '1:33691177803:web:944312ed009175b3becece',
    messagingSenderId: '33691177803',
    projectId: 'ecommerce-pro-392ca',
    authDomain: 'ecommerce-pro-392ca.firebaseapp.com',
    storageBucket: 'ecommerce-pro-392ca.firebasestorage.app',
    measurementId: 'G-PH1HGSHR4F',
  );
}
